image: alpine:latest

.runner: &runner
  tags:
  - runner:main

stages:
- echo
- deploy

echo:
  <<: *runner
  stage: echo
  script:
  - echo ${CI_PIPELINE_ID}
  - echo ${CI_JOB_STAGE}
  - echo ${CI_JOB_ID}
  
allowed_fail:
  <<: *runner
  stage: echo
  script: 
  - /bin/waaaaaaaat
  allow_failure: true
  
deploy:
 <<: *runner
 stage: deploy
 script:
 - echo "DEPLOYING test-env"
 environment:
   name: test-env
   url: "http://example.com"
 when: manual
 
