# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  datadog-agent: datadog/agent@dev:alpha
jobs:
  echo:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: echo "${CIRCLE_WORKFLOW_ID}"
      - run: echo "${CIRCLE_JOB}"
      - run: echo "${CIRCLE_BUILD_NUM}"
      - run: echo "${CIRCLE_BUILD_URL}"
      - run: echo "${CIRCLECI_TOKEN}"
      - run: echo "${CIRCLE_TOKEN}"
      - run:
          name: "Custom span"
          command: ./customspansparent.sh
          environment:
            DATADOG_SITE: datad0g.com
  agent-tester:
    docker:
      - image: python:3.9.7-buster
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get -y install curl
      - datadog-agent/setup:
          agent_major_version: "7"
          api_key: TEST_VALUE
          site: datad0g.com
      - run: service datadog-agent status
      - run: cat /etc/datadog-agent/datadog.yaml
      - run: pip3 install -r ./python_tests/requirements.txt
      - run: DD_ENV=carlos-test DD_SERVICE=carlos-testing pytest python_tests/ --ddtrace
      - run:
          name: Sleep
          command: sleep 30
          when: always
      - datadog-agent/stop
        
workflows:
  echo:
    jobs:
      - echo
  orb-test:
    jobs:
      - agent-tester
    
