# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  datadog-agent: datadog/agent@3.1.0
jobs:
  echo:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: echo "${CIRCLE_WORKFLOW_ID}"
      - run: echo "${CIRCLE_JOB}"
      - run: echo "${CIRCLE_BUILD_NUM}"
      - run: echo "${CIRCLE_BUILD_URL}"
      - run: echo "${CIRCLECI_TOKEN}"
      - run: echo "${CIRCLE_TOKEN}"
      - run:
          name: "Custom span"
          command: ./customspansparent.sh
          environment:
            DATADOG_SITE: datad0g.com
  agent-tester:
    docker:
      - image: ubuntu:18.04
    environment:
      DD_SITE: datad0g.com
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get -y install curl python3.8 python3-pip
      - run: pip3 install --upgrade pip
      - datadog-agent/setup:
          api_key: DATADOG_API_KEY
      - run: pip3 install -r ./python_tests/requirements.txt
      - run: DD_ENV=carlos-test DD_SERVICE=carlos-testing pytest python_tests/ --ddtrace
      - datadog-agent/stop
        
workflows:
  echo:
    jobs:
      - echo
  orb-test:
    when:
        condition:
          equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - agent-tester
    
