agents:
  queue: "carlos"

steps:
  - command: python3 .buildkite/custom_tags.py pipeline "team:ci-app"
    label: pipeline custom tags
  - commands: .buildkite/run_buildkite_test.sh
    label: run tests
    artifact_paths: test.xml
