agents:
  queue: "carlos"

steps:
  - command: go version
    label: Go version
    concurrency_group: buildkite-sample/version
    concurrency: 2
  - command: go clean -testcache
    label: Clean go test cache
  - command: gotestsum --format testname --junitfile test.xml
    label: run tests
    retry:
      automatic:
        - exit_status: '*'
          limit: 3
  - command: datadog-ci junit upload --service "carlos-test" test.xml 
    artifact_paths: test.xml
    label: Upload test to DataDog
