agents:
  queue: "carlos"

steps:
  - command: buildkite-agent meta-data set "dd.go.version" $(go version)
    label: Go version
  - commands: .buildkite/run_buildkite_test.sh
    label: run tests
    artifact_paths: test.xml

