agents:
  queue: "carlos"

steps:
  - command: buildkite-agent meta-data set "dd_tags.buildkite.size" 7
  - command: buildkite-agent meta-data set "dd_tags.buildkite.count" 10
  - command: go version | tr -d '\n' | buildkite-agent meta-data set "dd.go.version"
    label: Go version
  - commands: .buildkite/run_buildkite_test.sh
    label: run tests
    artifact_paths: test.xml

