name: 'Stop Agent'
description: 'Stop Datadog docker agent'
inputs:
  containerName:  # id of input
    description: 'The datadog-agent docker container name'
    required: true
    default: 'datadog-agent'
  registryPath:
    description: 'The docker registry to use'
    required: true
    default: 'datadog/agent'
  apiKey:
    description: 'The Datadog API key'
    required: true
  site:
    description: 'The Datadog site'
    required: true
    default: "datadoghq.com"
runs:
  using: 'node16'
  main: 'index.js'
  post: 'stop.js'