name: Webhooks Test GitHub Actions
on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: gcr.io/datadoghq/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./python_tests/requirements.txt
      - name: Test with pytest
        run: |
          python -m pip install -r requirements.txt
          export PYTHONPATH=src
          DD_ENV=carlos-test DD_SERVICE=carlos-testing DD_AGENT_HOST=datadog-agent pytest python_tests/ --ddtrace
