name: Webhooks Test GitHub Actions
on: [push, workflow_dispatch]

jobs:
  agent-job:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Datadog Agent Setup
        uses: DataDog/agent-github-action@v1.3
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          datadog_site: "datad0g.com"
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./python_tests/requirements.txt
      - name: Test with pytest
        run: |
          DD_ENV=carlos-test DD_SERVICE=carlos-testing pytest python_tests/ --ddtrace
  go-tests:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install gotest.tools/gotestsum@latest
      - run: gotestsum --junitfile test.xml ./gotests
      - uses: datadog/junit-upload-github-action@v1
        if: always()
        with:
            api-key: ${{ secrets.DD_API_KEY }}
            service: ci-webhooks-test-ci
            env: ci-tests-${{matrix.os}}
            files: test.xml
            datadog-site: datad0g.com
